// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	DeleteUser(ctx context.Context, id int32) error
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error
}

var _ Querier = (*Queries)(nil)
